version: '2.1'
services:
  base:
    build:
      context: .
      dockerfile: ./dockerfile
  server:
      extends: base
      command: yarn start
      environment:
        - NODE_ENV=test
        - DATABASE_HOST=database
      ports:
        - 3003:3003
      links:
          - database
  database:
    image: postgres:9.6.5-alpine
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: